/**
 * Sovereign Archive Design System
 * Color palette, typography, and spacing tokens
 */

export const sovereignArchiveTheme = {
  colors: {
    primary: {
      container: "#002147",
      fixed: "#d6e3ff",
      fixedDim: "#aec7f6",
      on: "#ffffff",
      onContainer: "#708ab5",
      onFixed: "#001b3d",
      onFixedVariant: "#2d476f",
      inverse: "#aec7f6",
    },
    secondary: {
      DEFAULT: "#006d42",
      container: "#56ffab",
      fixed: "#56ffab",
      fixedDim: "#2ce191",
      on: "#ffffff",
      onContainer: "#007346",
      onFixed: "#002110",
      onFixedVariant: "#005230",
    },
    tertiary: {
      DEFAULT: "#140800",
      container: "#331d00",
      fixed: "#ffddb8",
      fixedDim: "#ffb95f",
      on: "#ffffff",
      onContainer: "#bf7a00",
      onFixed: "#2a1700",
      onFixedVariant: "#653e00",
    },
    accent: "#00D384",
    error: "#ba1a1a",
    onError: "#ffffff",
    errorContainer: "#ffdad6",
    onErrorContainer: "#93000a",
    surface: {
      DEFAULT: "#faf8ff",
      bright: "#faf8ff",
      container: "#eaedff",
      containerHigh: "#e3e7ff",
      containerHighest: "#dce1fb",
      containerLow: "#f2f3ff",
      containerLowest: "#ffffff",
      dim: "#d4d9f2",
      tint: "#465f88",
      variant: "#dce1fb",
      onVariant: "#44474e",
      on: "#151b2d",
      onVariantAlt: "#44474e",
    },
    background: "#faf8ff",
    onBackground: "#151b2d",
    outline: "#74777f",
    outlineVariant: "#c4c6cf",
    inverseSurface: "#2a3043",
    inverseOnSurface: "#eef0ff",
    scrim: "#000000",
  },
  typography: {
    h1: {
      fontSize: "48px",
      fontFamily: "Manrope",
      fontWeight: 700,
      lineHeight: "1.2",
      letterSpacing: "-0.02em",
    },
    h2: {
      fontSize: "36px",
      fontFamily: "Manrope",
      fontWeight: 600,
      lineHeight: "1.3",
      letterSpacing: "-0.01em",
    },
    h3: {
      fontSize: "24px",
      fontFamily: "Manrope",
      fontWeight: 600,
      lineHeight: "1.4",
      letterSpacing: "0",
    },
    bodyLg: {
      fontSize: "18px",
      fontFamily: "Inter",
      fontWeight: 400,
      lineHeight: "1.6",
    },
    bodyMd: {
      fontSize: "16px",
      fontFamily: "Inter",
      fontWeight: 400,
      lineHeight: "1.5",
    },
    bodySm: {
      fontSize: "14px",
      fontFamily: "Inter",
      fontWeight: 400,
      lineHeight: "1.5",
    },
    labelCaps: {
      fontSize: "12px",
      fontFamily: "Inter",
      fontWeight: 600,
      lineHeight: "1",
      letterSpacing: "0.05em",
    },
  },
  spacing: {
    xs: "4px",
    sm: "12px",
    base: "8px",
    md: "24px",
    gutter: "24px",
    lg: "48px",
    xl: "80px",
    margin: "32px",
  },
  borderRadius: {
    sm: "2px",
    md: "4px",
    lg: "8px",
    xl: "12px",
    full: "12px",
  },
} as const;

export type SovereignArchiveTheme = typeof sovereignArchiveTheme;
